#ifndef ATMEGA128REGMAP_H_
#define ATMEGA128REGMAP_H_

#include <stdint.h>


#define UCSR1C    *((volatile uint8_t *)0x9D)
#define UDR1      *((volatile uint8_t *)0x9C)
#define UCSR1A    *((volatile uint8_t *)0x9B)
#define UCSR1B    *((volatile uint8_t *)0x9A)
#define UBRR1L    *((volatile uint8_t *)0x99)
#define UBRR1H    *((volatile uint8_t *)0x98)
#define UCSR0C    *((volatile uint8_t *)0x95)
#define UBRR0H    *((volatile uint8_t *)0x90)


#define TCCR3C    *((volatile uint8_t *)0x8C)
#define TCCR3A    *((volatile uint8_t *)0x8B)
#define TCCR3B    *((volatile uint8_t *)0x8A)
#define TCNT3H    *((volatile uint8_t *)0x89)
#define TCNT3L    *((volatile uint8_t *)0x88)
#define OCR3AH    *((volatile uint8_t *)0x87)
#define OCR3AL    *((volatile uint8_t *)0x86)
#define OCR3BH    *((volatile uint8_t *)0x85)
#define OCR3BL    *((volatile uint8_t *)0x84)
#define OCR3CH    *((volatile uint8_t *)0x83)
#define OCR3CL    *((volatile uint8_t *)0x82)
#define ICR3H     *((volatile uint8_t *)0x81)
#define ICR3L     *((volatile uint8_t *)0x80)


#define ETIMSK    *((volatile uint8_t *)0x7D)
#define ETIFR     *((volatile uint8_t *)0x7C)
#define TCCR1C    *((volatile uint8_t *)0x7A)
#define OCR1CH    *((volatile uint8_t *)0x79)
#define OCR1CL    *((volatile uint8_t *)0x78)
#define TWCR      *((volatile uint8_t *)0x74)
#define TWDR      *((volatile uint8_t *)0x73)
#define TWAR      *((volatile uint8_t *)0x72)
#define TWSR      *((volatile uint8_t *)0x71)
#define TWBR      *((volatile uint8_t *)0x70)

#define OSCCAL    *((volatile uint8_t *)0x6F)
#define XMCRA     *((volatile uint8_t *)0x6D)
#define PORTG     *((volatile uint8_t *)0x65)
#define DDRG      *((volatile uint8_t *)0x64)
#define PING      *((volatile uint8_t *)0x63)
#define PORTF     *((volatile uint8_t *)0x62)
#define DDRF      *((volatile uint8_t *)0x61)


#define SREG      *((volatile uint8_t *)0x5F)
#define SPH       *((volatile uint8_t *)0x5E)
#define SPL       *((volatile uint8_t *)0x5D)
#define XDIV      *((volatile uint8_t *)0x5C)
#define RAMPZ     *((volatile uint8_t *)0x5B)
#define EICRB     *((volatile uint8_t *)0x5A)
#define EIMSK     *((volatile uint8_t *)0x59)
#define EIFR      *((volatile uint8_t *)0x58)
#define TIMSK     *((volatile uint8_t *)0x57)
#define TIFR      *((volatile uint8_t *)0x56)
#define MCUCR     *((volatile uint8_t *)0x55)
#define MCUCSR    *((volatile uint8_t *)0x54)
#define TCCR0     *((volatile uint8_t *)0x53)
#define TCNT0     *((volatile uint8_t *)0x52)
#define OCR0      *((volatile uint8_t *)0x51)
#define ASSR      *((volatile uint8_t *)0x50)


#define TCCR1A    *((volatile uint8_t *)0x4F)
#define TCCR1B    *((volatile uint8_t *)0x4E)
#define TCNT1H    *((volatile uint8_t *)0x4D)
#define TCNT1L    *((volatile uint8_t *)0x4C)
#define OCR1AH    *((volatile uint8_t *)0x4B)
#define OCR1AL    *((volatile uint8_t *)0x4A)
#define OCR1BH    *((volatile uint8_t *)0x49)
#define OCR1BL    *((volatile uint8_t *)0x48)
#define WDTCR     *((volatile uint8_t *)0x41)
#define OCDR      *((volatile uint8_t *)0x42)
#define EICRA     *((volatile uint8_t *)0x40)


#define SPMCSR    *((volatile uint8_t *)0x3E)
#define PORTA     *((volatile uint8_t *)0x3B)
#define DDRA      *((volatile uint8_t *)0x3A)
#define PINA      *((volatile uint8_t *)0x39)
#define PORTB     *((volatile uint8_t *)0x38)
#define DDRB      *((volatile uint8_t *)0x37)
#define PINB      *((volatile uint8_t *)0x36)
#define PORTC     *((volatile uint8_t *)0x35)
#define DDRC      *((volatile uint8_t *)0x34)
#define PINC      *((volatile uint8_t *)0x33)
#define PORTD     *((volatile uint8_t *)0x32)
#define DDRD      *((volatile uint8_t *)0x31)
#define PIND      *((volatile uint8_t *)0x30)


#define SPDR      *((volatile uint8_t *)0x2F)
#define SPSR      *((volatile uint8_t *)0x2E)
#define SPCR      *((volatile uint8_t *)0x2D)
#define UDR0      *((volatile uint8_t *)0x2C)
#define UCSR0A    *((volatile uint8_t *)0x2B)
#define UCSR0B    *((volatile uint8_t *)0x2A)
#define UBRR0L    *((volatile uint8_t *)0x29)
#define ACSR      *((volatile uint8_t *)0x28)
#define ADMUX     *((volatile uint8_t *)0x27)
#define ADCSRA    *((volatile uint8_t *)0x26)
#define ADCH      *((volatile uint8_t *)0x25)
#define ADCL      *((volatile uint8_t *)0x24)
#define PORTE     *((volatile uint8_t *)0x23)
#define DDRE      *((volatile uint8_t *)0x22)
#define PINE      *((volatile uint8_t *)0x21)
#define PINF      *((volatile uint8_t *)0x20)

#endif /* ATMEGA128REGMAP_H_ */